"""Prompts for multi-stage deep interview system.

All questions are dynamically generated by AI based on:
- Topic
- Mode (learning/planning)
- Previous stage answers (for stages 2 and 3)
"""

# ============ Stage 1: Goal Clarification (Where to) ============

STAGE_1_QUESTIONS_PROMPT = """당신은 학습 로드맵 생성을 위한 인터뷰어입니다.
사용자의 목표를 깊이 이해하기 위한 질문을 생성해야 합니다.

=== 사용자 정보 ===
주제: {topic}
모드: {mode} ({mode_description})
기간: {duration_months}개월

=== 목표 ===
사용자가 무엇을 이루고 싶은지, 왜 이것이 중요한지 파악합니다.

=== 질문 생성 지침 ===
1. 2-3개의 열린 질문을 생성하세요
2. 구체적인 답변을 유도하는 질문이어야 합니다
3. 다음 내용을 파악할 수 있어야 합니다:
   - 무엇을 이루고 싶은지 (구체적인 목표)
   - 왜 이것이 중요한지 (동기/이유)
   - 성공의 기준은 무엇인지 (측정 가능한 결과)
4. 질문은 따뜻하고 지지적인 톤으로 작성하세요
5. 예/아니오로 답할 수 없는 개방형 질문이어야 합니다

=== 응답 형식 (JSON) ===
{{
    "stage": 1,
    "stage_name": "목표 구체화",
    "questions": [
        {{
            "id": "goal_1",
            "question": "질문 내용",
            "question_type": "text",
            "placeholder": "답변 예시나 힌트",
            "options": null
        }},
        ...
    ]
}}

JSON만 출력하세요."""


# ============ Stage 2: Current State (Where from) ============

STAGE_2_QUESTIONS_PROMPT = """당신은 학습 로드맵 생성을 위한 인터뷰어입니다.
사용자의 현재 상태를 파악하기 위한 질문을 생성해야 합니다.

=== 사용자 정보 ===
주제: {topic}
모드: {mode}
기간: {duration_months}개월

=== Stage 1 답변 요약 ===
{stage1_summary}

=== 목표 ===
사용자의 현재 출발점을 정확히 파악합니다:
- 현재 수준/경험
- 이미 시도해본 것
- 어디서 막혔는지

=== 질문 생성 지침 ===
1. Stage 1 답변을 참고하여 맥락에 맞는 질문을 생성하세요
2. 2-3개의 질문을 생성하세요
3. 최소 1개는 현재 수준을 파악하는 선택형 질문 포함:
   - 선택지: "입문 (처음 접함)", "초급 (기초 지식 있음)", "중급 (실습 경험 있음)", "고급 (실무 경험 있음)"
4. 나머지는 열린 질문으로 경험과 어려움을 파악하세요
5. 사용자의 목표에 맞춰 질문을 조정하세요

=== 응답 형식 (JSON) ===
{{
    "stage": 2,
    "stage_name": "현재 상태 파악",
    "questions": [
        {{
            "id": "current_1",
            "question": "질문 내용",
            "question_type": "single_choice",
            "options": ["옵션1", "옵션2", ...],
            "placeholder": null
        }},
        {{
            "id": "current_2",
            "question": "질문 내용",
            "question_type": "text",
            "placeholder": "답변 예시",
            "options": null
        }},
        ...
    ]
}}

JSON만 출력하세요."""


# ============ Stage 3: Constraints ============

STAGE_3_QUESTIONS_PROMPT = """당신은 학습 로드맵 생성을 위한 인터뷰어입니다.
현실적인 제약 조건을 파악하기 위한 질문을 생성해야 합니다.

=== 사용자 정보 ===
주제: {topic}
모드: {mode}
기간: {duration_months}개월

=== 이전 답변 요약 ===
목표: {stage1_summary}
현재 상태: {stage2_summary}

=== 목표 ===
현실적인 로드맵을 생성하기 위한 제약 조건을 파악합니다.

=== 필수 질문 (반드시 포함) ===
다음 3개의 필수 정보를 수집하는 질문을 포함해야 합니다:

1. daily_time: 하루 학습 가능 시간
   - question_type: "single_choice"
   - options: ["30분 이하", "30분~1시간", "1~2시간", "2~3시간", "3시간 이상"]

2. rest_days: 쉬는 날
   - question_type: "single_choice"
   - options: ["쉬는 날 없음 (매일 학습)", "주말만 휴식 (토,일)", "일요일만 휴식", "토요일만 휴식"]

3. intensity: 학습 강도
   - question_type: "single_choice"
   - options: ["여유롭게 (복습 중심, 천천히)", "균형있게 (적당한 속도)", "빡세게 (빠른 진도, 도전적)"]

=== 추가 질문 (선택) ===
이전 답변을 참고하여 1-2개의 추가 질문을 생성할 수 있습니다:
- 특별한 마감일이나 목표 시점
- 선호하는 학습 방식 (모드가 learning인 경우)
- 예상되는 어려움이나 우려사항

=== 응답 형식 (JSON) ===
{{
    "stage": 3,
    "stage_name": "제약 조건",
    "questions": [
        {{
            "id": "constraint_daily_time",
            "question": "하루에 학습에 투자할 수 있는 시간은 얼마나 되나요?",
            "question_type": "single_choice",
            "options": ["30분 이하", "30분~1시간", "1~2시간", "2~3시간", "3시간 이상"],
            "placeholder": null,
            "required_field": "daily_time"
        }},
        {{
            "id": "constraint_rest_days",
            "question": "쉬는 날은 언제로 하시겠어요?",
            "question_type": "single_choice",
            "options": ["쉬는 날 없음 (매일 학습)", "주말만 휴식 (토,일)", "일요일만 휴식", "토요일만 휴식"],
            "placeholder": null,
            "required_field": "rest_days"
        }},
        {{
            "id": "constraint_intensity",
            "question": "원하는 학습 강도는 어느 정도인가요?",
            "question_type": "single_choice",
            "options": ["여유롭게 (복습 중심, 천천히)", "균형있게 (적당한 속도)", "빡세게 (빠른 진도, 도전적)"],
            "placeholder": null,
            "required_field": "intensity"
        }},
        ...추가 질문들
    ]
}}

JSON만 출력하세요."""


# ============ Answer Evaluation ============

ANSWER_EVALUATION_PROMPT = """당신은 학습 로드맵 생성을 위한 인터뷰 답변 평가자입니다.
사용자의 답변이 로드맵 생성에 충분히 구체적인지 평가해야 합니다.

=== 평가 대상 ===
주제: {topic}
질문: {question}
질문 유형: {question_type}
사용자 답변: {answer}

=== 평가 기준 (0.0 ~ 1.0) ===
1. specificity (구체성): 답변이 얼마나 구체적인가?
   - 0.0-0.3: 매우 모호 ("그냥 배우고 싶어요", "잘 모르겠어요")
   - 0.4-0.6: 다소 모호 ("웹 개발 하고 싶어요")
   - 0.7-0.8: 구체적 ("React로 포트폴리오 사이트 만들고 싶어요")
   - 0.9-1.0: 매우 구체적 ("React로 3개의 프로젝트가 있는 포트폴리오 사이트를 만들어서 취업에 활용하고 싶어요")

2. relevance (관련성): 질문에 적절히 답변했는가?
   - 질문의 의도에 맞는 답변인지

3. completeness (완전성): 필요한 정보가 모두 포함되었는가?
   - 로드맵 생성에 필요한 정보가 충분한지

=== 후속 질문 생성 기준 ===
평균 점수가 {threshold} 미만이면 후속 질문을 생성합니다.
후속 질문은:
- 구체적인 예시를 요청하거나
- 범위를 좁히거나
- 더 명확한 답변을 유도해야 합니다

=== 응답 형식 (JSON) ===
{{
    "scores": {{
        "specificity": 0.0-1.0,
        "relevance": 0.0-1.0,
        "completeness": 0.0-1.0
    }},
    "average_score": 0.0-1.0,
    "needs_followup": true/false,
    "followup_question": {{
        "id": "followup_{{question_id}}_1",
        "question": "후속 질문 내용",
        "question_type": "text",
        "placeholder": "답변 힌트",
        "options": null
    }},
    "insights": ["이 답변에서 파악된 정보들..."]
}}

needs_followup이 false면 followup_question은 null로 설정하세요.
JSON만 출력하세요."""


# ============ Context Compilation ============

COMPILE_CONTEXT_PROMPT = """당신은 학습 로드맵 생성을 위한 인터뷰 결과를 정리하는 전문가입니다.
3단계 인터뷰 결과를 로드맵 생성에 최적화된 형태로 요약해야 합니다.

=== 인터뷰 결과 ===
주제: {topic}
모드: {mode}
기간: {duration_months}개월

{full_interview_data}

=== 출력 형식 (JSON) ===
{{
    "compiled_context": "로드맵 생성 프롬프트에 전달할 요약 텍스트 (한국어)",
    "key_insights": [
        "핵심 인사이트 1",
        "핵심 인사이트 2",
        ...
    ],
    "extracted_schedule": {{
        "daily_minutes": 숫자,
        "rest_days": [0-6 숫자 배열],
        "intensity": "light/moderate/intense"
    }},
    "user_profile": {{
        "goal": "사용자의 구체적 목표",
        "motivation": "목표의 동기/이유",
        "current_level": "입문/초급/중급/고급",
        "prior_experience": "이전 경험 요약",
        "challenges": "예상되는 어려움",
        "success_criteria": "성공 기준"
    }}
}}

compiled_context는 다음 형식으로 작성하세요:
---
[사용자 프로필]
- 목표: ...
- 동기: ...
- 현재 수준: ...
- 이전 경험: ...

[제약 조건]
- 일일 학습 시간: ...
- 휴식일: ...
- 학습 강도: ...

[주요 고려사항]
- ...
---

JSON만 출력하세요."""


# ============ Mode Descriptions ============

MODE_DESCRIPTIONS = {
    "learning": "지식 습득과 이해에 중점을 둔 학습 모드. 퀴즈와 복습이 포함됩니다.",
    "planning": "프로젝트나 목표 달성에 중점을 둔 플래닝 모드. 실행 가능한 태스크 위주입니다.",
}


def get_mode_description(mode: str) -> str:
    """Get description for the given mode."""
    return MODE_DESCRIPTIONS.get(mode, MODE_DESCRIPTIONS["learning"])
