"""add_learning_mode_tables

Revision ID: f825b454faf5
Revises: 005
Create Date: 2025-12-07 07:43:24.359763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f825b454faf5'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 0. questiontype enum 생성 (없으면 생성)
    op.execute('''
        DO $$ BEGIN
            CREATE TYPE questiontype AS ENUM ('multiple_choice', 'short_answer', 'essay');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    ''')

    # 1. daily_feedbacks 테이블 생성 (신규)
    op.create_table('daily_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_task_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_task_id'], ['weekly_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # 2. daily_tasks 테이블에 Learning 모드 필드 추가
    op.add_column('daily_tasks', sa.Column('is_review_task', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('daily_tasks', sa.Column('review_source_ids', postgresql.ARRAY(sa.UUID()), nullable=True))

    # 3. weekly_tasks 테이블에 Learning 모드 필드 추가
    op.add_column('weekly_tasks', sa.Column('review_generated', sa.Boolean(), server_default='false', nullable=False))

    # 4. user_answers 및 questions 테이블 재생성 (CASCADE DROP 사용)
    op.execute('DROP TABLE IF EXISTS user_answers CASCADE')
    op.execute('DROP TABLE IF EXISTS questions CASCADE')

    # 5. questions 테이블 생성 (기존 questiontype enum 재사용)
    op.execute('''
        CREATE TABLE questions (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            daily_task_id UUID NOT NULL REFERENCES daily_tasks(id) ON DELETE CASCADE,
            question_type questiontype NOT NULL,
            question_text TEXT NOT NULL,
            choices JSONB,
            correct_answer TEXT NOT NULL,
            hint TEXT,
            explanation TEXT,
            "order" INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
        )
    ''')

    # 6. user_answers 테이블 생성
    op.execute('''
        CREATE TABLE user_answers (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
            user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            answer_text TEXT NOT NULL,
            is_correct BOOLEAN,
            score INTEGER,
            feedback TEXT,
            submitted_at TIMESTAMP WITH TIME ZONE,
            graded_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
        )
    ''')

    # 7. 기존 레거시 테이블 삭제 (CASCADE 사용)
    op.execute('DROP TABLE IF EXISTS quizzes CASCADE')
    op.execute('ALTER TABLE IF EXISTS roadmaps DROP COLUMN IF EXISTS interview_response_id')
    op.execute('DROP TABLE IF EXISTS interview_responses CASCADE')
    op.execute('DROP TABLE IF EXISTS interview_sessions CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_tasks', 'review_generated')
    op.add_column('user_answers', sa.Column('selected_option', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_answers_question_id_key', 'user_answers', ['question_id'])
    op.alter_column('user_answers', 'score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('user_answers', 'answer_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('user_answers', 'graded_at')
    op.drop_column('user_answers', 'submitted_at')
    op.add_column('roadmaps', sa.Column('interview_response_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('roadmaps_interview_response_id_fkey', 'roadmaps', 'interview_responses', ['interview_response_id'], ['id'], ondelete='SET NULL')
    op.add_column('questions', sa.Column('quiz_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('question_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quiz_id_fkey', 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('questions', 'order')
    op.drop_column('questions', 'hint')
    op.drop_column('questions', 'choices')
    op.drop_column('questions', 'daily_task_id')
    op.drop_column('daily_tasks', 'review_source_ids')
    op.drop_column('daily_tasks', 'is_review_task')
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_stage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('in_progress', 'completed', 'abandoned', 'terminated', name='interviewstatus'), autoincrement=False, nullable=False),
    sa.Column('stage_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('current_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('current_answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('current_evaluations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('followup_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_followup_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('max_followups_per_stage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('compiled_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_daily_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extracted_rest_days', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extracted_intensity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('roadmap_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('current_round', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_rounds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('all_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('all_answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('evaluations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('invalid_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('invalid_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consecutive_invalid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_terminated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('termination_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('warning_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name='interview_sessions_roadmap_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='interview_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='interview_sessions_pkey')
    )
    op.create_index('ix_interview_sessions_user_id', 'interview_sessions', ['user_id'], unique=False)
    op.create_index('ix_interview_sessions_status', 'interview_sessions', ['status'], unique=False)
    op.create_table('interview_responses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('skill_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('related_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('daily_available_hours', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('preferred_learning_styles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('learning_purpose', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('specific_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_questions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('ai_answers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('learner_profile', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.VARCHAR(length=10), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='interview_responses_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='interview_responses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_interview_responses_user_id', 'interview_responses', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('daily_task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'GRADED', name='quizstatus'), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('correct_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['daily_task_id'], ['daily_tasks.id'], name='quizzes_daily_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='quizzes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quizzes_pkey')
    )
    op.drop_table('daily_feedbacks')
    # ### end Alembic commands ###
