from app.schemas.user import (
    UserBase,
    UserCreate,
    UserLogin,
    UserUpdate,
    UserResponse,
    UserInDB,
)
from app.schemas.auth import (
    Token,
    TokenPayload,
    AuthResponse,
    RefreshTokenRequest,
)
from app.schemas.roadmap import (
    DailyTaskBase,
    DailyTaskCreate,
    DailyTaskResponse,
    WeeklyTaskBase,
    WeeklyTaskCreate,
    WeeklyTaskResponse,
    WeeklyTaskWithDaily,
    MonthlyGoalBase,
    MonthlyGoalCreate,
    MonthlyGoalResponse,
    MonthlyGoalWithWeekly,
    MonthlyGoalFull,
    RoadmapBase,
    RoadmapCreate,
    RoadmapUpdate,
    RoadmapResponse,
    RoadmapWithMonthly,
    RoadmapFull,
)
from app.schemas.quiz import (
    QuestionBase,
    QuestionCreate,
    QuestionResponse,
    QuestionWithAnswer,
    UserAnswerBase,
    UserAnswerCreate,
    UserAnswerResponse,
    SubmitAnswerRequest,
    QuizBase,
    QuizCreate,
    QuizResponse,
    QuizWithQuestions,
    QuizDetail,
    QuizResult,
    QuizGenerateRequest,
    QuizGenerateResponse,
    QuizSubmitRequest,
    QuizSubmitResponse,
)

__all__ = [
    # User
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    # Auth
    "Token",
    "TokenPayload",
    "AuthResponse",
    "RefreshTokenRequest",
    # Roadmap
    "DailyTaskBase",
    "DailyTaskCreate",
    "DailyTaskResponse",
    "WeeklyTaskBase",
    "WeeklyTaskCreate",
    "WeeklyTaskResponse",
    "WeeklyTaskWithDaily",
    "MonthlyGoalBase",
    "MonthlyGoalCreate",
    "MonthlyGoalResponse",
    "MonthlyGoalWithWeekly",
    "MonthlyGoalFull",
    "RoadmapBase",
    "RoadmapCreate",
    "RoadmapUpdate",
    "RoadmapResponse",
    "RoadmapWithMonthly",
    "RoadmapFull",
    # Quiz
    "QuestionBase",
    "QuestionCreate",
    "QuestionResponse",
    "QuestionWithAnswer",
    "UserAnswerBase",
    "UserAnswerCreate",
    "UserAnswerResponse",
    "SubmitAnswerRequest",
    "QuizBase",
    "QuizCreate",
    "QuizResponse",
    "QuizWithQuestions",
    "QuizDetail",
    "QuizResult",
    "QuizGenerateRequest",
    "QuizGenerateResponse",
    "QuizSubmitRequest",
    "QuizSubmitResponse",
]
