from app.schemas.user import (
    UserBase,
    UserCreate,
    UserLogin,
    UserUpdate,
    UserResponse,
    UserInDB,
)
from app.schemas.auth import (
    Token,
    TokenPayload,
    AuthResponse,
    RefreshTokenRequest,
    RegisterResponse,
    EmailVerificationRequest,
    EmailVerificationResponse,
    ResendVerificationRequest,
    ResendVerificationResponse,
)
from app.schemas.roadmap import (
    DailyTaskBase,
    DailyTaskCreate,
    DailyTaskResponse,
    DailyTaskUpdate,
    DailyTaskReorder,
    DailyTaskReorderRequest,
    WeeklyTaskBase,
    WeeklyTaskCreate,
    WeeklyTaskResponse,
    WeeklyTaskWithDaily,
    WeeklyTaskUpdate,
    MonthlyGoalBase,
    MonthlyGoalCreate,
    MonthlyGoalResponse,
    MonthlyGoalWithWeekly,
    MonthlyGoalFull,
    MonthlyGoalUpdate,
    RoadmapBase,
    RoadmapCreate,
    RoadmapUpdate,
    RoadmapResponse,
    RoadmapWithMonthly,
    RoadmapFull,
    RoadmapScheduleUpdate,
    RoadmapFinalizeResponse,
)
from app.schemas.interview import (
    InterviewQuestion,
    InterviewAnswer,
    InterviewContext,
    InterviewStartRequest,
    InterviewStartResponse,
    InterviewSubmitRequest,
    InterviewSubmitResponse,
)
from app.schemas.unified_view import (
    TodayDailyTask,
    WeeklyTaskSummary,
    UnifiedViewResponse,
)

__all__ = [
    # User
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    # Auth
    "Token",
    "TokenPayload",
    "AuthResponse",
    "RefreshTokenRequest",
    "RegisterResponse",
    "EmailVerificationRequest",
    "EmailVerificationResponse",
    "ResendVerificationRequest",
    "ResendVerificationResponse",
    # Roadmap
    "DailyTaskBase",
    "DailyTaskCreate",
    "DailyTaskResponse",
    "DailyTaskUpdate",
    "DailyTaskReorder",
    "DailyTaskReorderRequest",
    "WeeklyTaskBase",
    "WeeklyTaskCreate",
    "WeeklyTaskResponse",
    "WeeklyTaskWithDaily",
    "WeeklyTaskUpdate",
    "MonthlyGoalBase",
    "MonthlyGoalCreate",
    "MonthlyGoalResponse",
    "MonthlyGoalWithWeekly",
    "MonthlyGoalFull",
    "MonthlyGoalUpdate",
    "RoadmapBase",
    "RoadmapCreate",
    "RoadmapUpdate",
    "RoadmapResponse",
    "RoadmapWithMonthly",
    "RoadmapFull",
    "RoadmapScheduleUpdate",
    "RoadmapFinalizeResponse",
    # Interview
    "InterviewQuestion",
    "InterviewAnswer",
    "InterviewContext",
    "InterviewStartRequest",
    "InterviewStartResponse",
    "InterviewSubmitRequest",
    "InterviewSubmitResponse",
    # Unified View
    "TodayDailyTask",
    "WeeklyTaskSummary",
    "UnifiedViewResponse",
]
